## 3. [50] Write a Python program (Jupyter notebook) that uses the data mining algorithms provided in SciKit-Learn to build knowledge models using the given hmwk10.csv.


### Preliminary upload data

In [0]:
from google.colab import files
uploaded = files.upload()

Saving hwk10.csv to hwk10.csv


In [0]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
import pandas as pd

data = pd.read_csv("hwk10.csv")
data.head()

A         B         C         D         E         F         G  H
0 -0.851789 -1.205610 -0.474291  0.313508 -0.452754 -0.381246 -1.414164  2
1 -2.243104  1.252614  0.118889 -0.569868 -1.536101  1.536289 -0.473938  2
2  1.096491 -0.736308  0.070911 -1.822606  1.662994  0.319114  2.321419  0
3  0.927066  2.737201  2.115261  1.826195  0.140160  0.758732  1.104514  2
4 -1.251867  0.147549  1.398634  0.418399  0.377142  0.911071  0.139122  1

### (a) [5] Create a set of unseen data (5 to 20 tuples).


In [0]:
from sklearn.model_selection import train_test_split

X = data.drop('H', axis = 1)
Y = np.asarray(data['H'], dtype="|S6")

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = .025)
len(y_test)

13

### (b) [15] Build a multiple level perceptron classifier and use it to classify several unseen
### data. Investigate the impact of number and size of hidden layers and the different activation functions

In [0]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

mlp.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [0]:
from sklearn.metrics import classification_report,confusion_matrix

predictions = mlp.predict(X_test)

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[6 0 0]
 [0 3 1]
 [0 0 3]]
              precision    recall  f1-score   support

        b'0'       1.00      1.00      1.00         6
        b'1'       1.00      0.75      0.86         4
        b'2'       0.75      1.00      0.86         3

   micro avg       0.92      0.92      0.92        13
   macro avg       0.92      0.92      0.90        13
weighted avg       0.94      0.92      0.92        13



### (c) [15] Build a support vector classifier and use it to classify the same set of unseen data.
### Investigate the effect of different types of kernel functions and their parameters

In [0]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.9230769230769231


### (d) [15] Build a K neighbors classifier and use it to classify the same set of unseen data.
### Investigate the impact of the number of neighbors and the metrics.

In [0]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training sets
model.fit(X_train,y_train)

#Predict Output
y_pred = model.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7692307692307693
